server:
  port: 8761
eureka:
  client:
    registerWithEureka: false #telling the built-in Eureka Client not to register with ‘itself' 
                              #because our application should be acting as a server.
                              
    fetchRegistry: false  